# Generated by Django 3.2.9 on 2021-12-09 17:30

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('softapp', '0002_alter_comment_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='contributor',
            name='permissions',
            field=models.CharField(choices=[('a', 'a'), ('c', 'c')], default=django.utils.timezone.now, max_length=2),
            preserve_default=False,
        ),
    ]
