# Generated by Django 3.2.9 on 2021-12-16 18:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('softapp', '0005_alter_contributor_project'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='contributor',
            unique_together=set(),
        ),
    ]
